const PRODUCTOS = [
  {
    "id": 1,
    "sku": 1,
    "nombre": "Aromanza (7 Poderes)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "7 Poderes",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 2,
    "sku": 2,
    "nombre": "Aromanza (Amazonas Salvaje)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Amazonas Salvaje",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 3,
    "sku": 3,
    "nombre": "Aromanza (Atrae Dinero)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Atrae Dinero",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 4,
    "sku": 4,
    "nombre": "Aromanza (Benjuí Delicioso)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Benjuí Delicioso",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 5,
    "sku": 5,
    "nombre": "Aromanza (Berry Kiss)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Berry Kiss",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 6,
    "sku": 6,
    "nombre": "Aromanza (Canela Mística)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Canela Mística",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 7,
    "sku": 7,
    "nombre": "Aromanza (Capuchino Italiano)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Capuchino Italiano",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 8,
    "sku": 8,
    "nombre": "Aromanza (Chandan)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Chandan",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 9,
    "sku": 9,
    "nombre": "Aromanza (Choco Dubai)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Choco Dubai",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 10,
    "sku": 10,
    "nombre": "Aromanza (Coco Beach)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Coco Beach",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 11,
    "sku": 11,
    "nombre": "Aromanza (Coco Vai)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Coco Vai",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 12,
    "sku": 12,
    "nombre": "Aromanza (Coconut)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Coconut",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 13,
    "sku": 13,
    "nombre": "Aromanza (Copal Andino)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Copal Andino",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 14,
    "sku": 14,
    "nombre": "Aromanza (Diamante Negro)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Diamante Negro",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 15,
    "sku": 15,
    "nombre": "Aromanza (Dulces Frutillas)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Dulces Frutillas",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 16,
    "sku": 16,
    "nombre": "Aromanza (Ébano Marfil)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Ébano Marfil",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 17,
    "sku": 17,
    "nombre": "Aromanza (Encanto de Chocolate)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Encanto de Chocolate",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 18,
    "sku": 18,
    "nombre": "Aromanza (Energía Limpia)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Energía Limpia",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 19,
    "sku": 19,
    "nombre": "Aromanza (Esencia de la India)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Esencia de la India",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 20,
    "sku": 20,
    "nombre": "Aromanza (Flores de Manzanilla)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Flores de Manzanilla",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 21,
    "sku": 21,
    "nombre": "Aromanza (Fragancia Oriental)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Fragancia Oriental",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 22,
    "sku": 22,
    "nombre": "Aromanza (Frescura del Bosque)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Frescura del Bosque",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 23,
    "sku": 23,
    "nombre": "Aromanza (Frutos Rojos)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Frutos Rojos",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 24,
    "sku": 24,
    "nombre": "Aromanza (Gardenias y Flores Blancas)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Gardenias y Flores Blancas",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 25,
    "sku": 25,
    "nombre": "Aromanza (Green Bambú)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Green Bambú",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 26,
    "sku": 26,
    "nombre": "Aromanza (Guía Espiritual)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Guía Espiritual",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 27,
    "sku": 27,
    "nombre": "Aromanza (Incienso Consagrado)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Incienso Consagrado",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 28,
    "sku": 28,
    "nombre": "Aromanza (Jazmín)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Jazmín",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 29,
    "sku": 29,
    "nombre": "Aromanza (Krishna)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Krishna",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 30,
    "sku": 30,
    "nombre": "Aromanza (La Vida es Bella)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "La Vida es Bella",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 31,
    "sku": 31,
    "nombre": "Aromanza (Lavanda del Valle)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Lavanda del Valle",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 32,
    "sku": 32,
    "nombre": "Aromanza (Limón Miel Orgánica)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Limón Miel Orgánica",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 33,
    "sku": 33,
    "nombre": "Aromanza (Magia Asiática)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Magia Asiática",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 34,
    "sku": 34,
    "nombre": "Aromanza (Manzana Canela)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Manzana Canela",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 35,
    "sku": 35,
    "nombre": "Aromanza (Mirra Consagrada)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Mirra Consagrada",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 36,
    "sku": 36,
    "nombre": "Aromanza (Mix Fragancias)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Mix Fragancias",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 37,
    "sku": 37,
    "nombre": "Aromanza (Naranja Pimienta)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Naranja Pimienta",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 38,
    "sku": 38,
    "nombre": "Aromanza (Néctar de los Dioses)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Néctar de los Dioses",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 39,
    "sku": 39,
    "nombre": "Aromanza (Noche de Ensueños)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Noche de Ensueños",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 40,
    "sku": 40,
    "nombre": "Aromanza (Opium Exotic)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Opium Exotic",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 41,
    "sku": 41,
    "nombre": "Aromanza (Pastelería Francesa)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Pastelería Francesa",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 42,
    "sku": 42,
    "nombre": "Aromanza (Pimpollos de Jazmín)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Pimpollos de Jazmín",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 43,
    "sku": 43,
    "nombre": "Aromanza (Placeres del Paraíso)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Placeres del Paraíso",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 44,
    "sku": 44,
    "nombre": "Aromanza (Premium Lemon)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Premium Lemon",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 45,
    "sku": 45,
    "nombre": "Aromanza (Protección Energética)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Protección Energética",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 46,
    "sku": 46,
    "nombre": "Aromanza (Ratnamala)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Ratnamala",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 47,
    "sku": 47,
    "nombre": "Aromanza (Real Champa)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Real Champa",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 48,
    "sku": 48,
    "nombre": "Aromanza (Real Rose)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Real Rose",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 49,
    "sku": 49,
    "nombre": "Aromanza (Reina de la Noche)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Reina de la Noche",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 50,
    "sku": 50,
    "nombre": "Aromanza (Rosa Real)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Rosa Real",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 51,
    "sku": 51,
    "nombre": "Aromanza (Sai Flora)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Sai Flora",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 52,
    "sku": 52,
    "nombre": "Aromanza (Sándalo Hindú)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Sándalo Hindú",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 53,
    "sku": 53,
    "nombre": "Aromanza (Salvia Blanca)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Salvia Blanca",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 54,
    "sku": 54,
    "nombre": "Aromanza (Super Palo Santo)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Super Palo Santo",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 55,
    "sku": 55,
    "nombre": "Aromanza (Titanium)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Titanium",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 56,
    "sku": 56,
    "nombre": "Aromanza (Vainilla Coco)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Vainilla Coco",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 57,
    "sku": 57,
    "nombre": "Aromanza (Vainilla Encantada)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Vainilla Encantada",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 58,
    "sku": 1,
    "nombre": "Aromanza (Violetas de Persia)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Violetas de Persia",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 59,
    "sku": 2,
    "nombre": "Aromanza (Viva la Vida)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Viva la Vida",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 60,
    "sku": 3,
    "nombre": "Aromanza (Vrindavan)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Vrindavan",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 61,
    "sku": 4,
    "nombre": "Aromanza (Wanama Coco)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Wanama Coco",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 62,
    "sku": 5,
    "nombre": "Aromanza (Yagra de la Abundancia)",
    "marca": "Aromanza",
    "linea": "Sahumerio Tibetano",
    "fragancia": "Yagra de la Abundancia",
    "costo": 1798,
    "venta": 3800,
    "stock": 0
  },
  {
    "id": 63,
    "sku": 6,
    "nombre": "Vela Larga Lisa Amarilla",
    "marca": "",
    "linea": "Vela Larga Lisa",
    "fragancia": "Amarilla",
    "costo": 183,
    "venta": 500,
    "stock": 0
  },
  {
    "id": 64,
    "sku": 7,
    "nombre": "Vela Larga Lisa Azul",
    "marca": "",
    "linea": "Vela Larga Lisa",
    "fragancia": "Azul",
    "costo": 183,
    "venta": 500,
    "stock": 0
  },
  {
    "id": 65,
    "sku": 8,
    "nombre": "Vela Larga Lisa Blanca",
    "marca": "",
    "linea": "Vela Larga Lisa",
    "fragancia": "Blanca",
    "costo": 183,
    "venta": 500,
    "stock": 0
  },
  {
    "id": 66,
    "sku": 9,
    "nombre": "Vela Larga Roja",
    "marca": "",
    "linea": "Vela Larga Lisa",
    "fragancia": "Vela Larga Roja",
    "costo": 183,
    "venta": 500,
    "stock": 0
  },
  {
    "id": 67,
    "sku": 10,
    "nombre": "Vela Larga Lisa Celeste",
    "marca": "",
    "linea": "Vela Larga Lisa",
    "fragancia": "Celeste",
    "costo": 183,
    "venta": 500,
    "stock": 0
  },
  {
    "id": 68,
    "sku": 11,
    "nombre": "Vela Larga Lisa Dorada",
    "marca": "",
    "linea": "Vela Larga Lisa",
    "fragancia": "Dorada",
    "costo": 183,
    "venta": 500,
    "stock": 0
  },
  {
    "id": 69,
    "sku": 12,
    "nombre": "Vela Larga Lisa Rosa",
    "marca": "",
    "linea": "Vela Larga Lisa",
    "fragancia": "Rosa",
    "costo": 183,
    "venta": 500,
    "stock": 0
  },
  {
    "id": 70,
    "sku": 13,
    "nombre": "Vela Larga Lisa Violeta",
    "marca": "",
    "linea": "Vela Larga Lisa",
    "fragancia": "Violeta",
    "costo": 183,
    "venta": 500,
    "stock": 0
  },
  {
    "id": 71,
    "sku": 14,
    "nombre": "Vela Larga Lisa Naranja",
    "marca": "",
    "linea": "Vela Larga Lisa",
    "fragancia": "Naranja",
    "costo": 183,
    "venta": 500,
    "stock": 0
  },
  {
    "id": 72,
    "sku": 15,
    "nombre": "Vela Larga Lisa Negra",
    "marca": "",
    "linea": "Vela Larga Lisa",
    "fragancia": "Negra",
    "costo": 183,
    "venta": 500,
    "stock": 0
  },
  {
    "id": 73,
    "sku": 16,
    "nombre": "Vela Larga Lisa Plateada",
    "marca": "",
    "linea": "Vela Larga Lisa",
    "fragancia": "Plateada",
    "costo": 183,
    "venta": 500,
    "stock": 0
  },
  {
    "id": 74,
    "sku": 19,
    "nombre": "Vela Larga Lisa Verde",
    "marca": "",
    "linea": "Vela Larga Lisa",
    "fragancia": "Verde",
    "costo": 183,
    "venta": 500,
    "stock": 0
  },
  {
    "id": 75,
    "sku": 20,
    "nombre": "Vela Larga Lisa Violeta",
    "marca": "",
    "linea": "Vela Larga Lisa",
    "fragancia": "Violeta",
    "costo": 183,
    "venta": 500,
    "stock": 0
  },
  {
    "id": 76,
    "sku": 76,
    "nombre": "Vela Larga 7 colores",
    "marca": "",
    "linea": "Vela Larga Lisa",
    "fragancia": "Vela Larga 7 colores",
    "costo": 0,
    "venta": 0,
    "stock": 0
  },
  {
    "id": 77,
    "sku": 76,
    "nombre": "Blanco - Negro (San La Muerte)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Blanco - Negro (San La Muerte)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 78,
    "sku": 77,
    "nombre": "Verde - Blanco - Rojo (San Jorge)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Verde - Blanco - Rojo (San Jorge)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 79,
    "sku": 78,
    "nombre": "Verde - Rojo (Expedito)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Verde - Rojo (Expedito)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 80,
    "sku": 79,
    "nombre": "Rojo - Blanco - Negro (Cipriano)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Rojo - Blanco - Negro (Cipriano)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 81,
    "sku": 80,
    "nombre": "Negro - Rojo (Exu)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Negro - Rojo (Exu)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 82,
    "sku": 81,
    "nombre": "Rojo - Negro (Pomba Gira)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Rojo - Negro (Pomba Gira)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 83,
    "sku": 82,
    "nombre": "Negro - Blanco (Preto)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Negro - Blanco (Preto)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 84,
    "sku": 83,
    "nombre": "Rojo - Blanco (Barbara)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Rojo - Blanco (Barbara)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 85,
    "sku": 84,
    "nombre": "Blanco - Rojo (Marcos Xango)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Blanco - Rojo (Marcos Xango)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 86,
    "sku": 85,
    "nombre": "Blanco - Amarillo (San Cayetano)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Blanco - Amarillo (San Cayetano)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 87,
    "sku": 86,
    "nombre": "Rojo - Verde (Catalina)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Rojo - Verde (Catalina)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 88,
    "sku": 87,
    "nombre": "Blanco - Celeste (Iemanja-Lourdes)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Blanco - Celeste (Iemanja-Lourdes)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 89,
    "sku": 88,
    "nombre": "Blanco - Verde (San Pantaleon)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Blanco - Verde (San Pantaleon)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 90,
    "sku": 89,
    "nombre": "Amarillo - Verde (Oxaña)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Amarillo - Verde (Oxaña)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 91,
    "sku": 90,
    "nombre": "Rosa - Celeste (Cosme y Damian)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Rosa - Celeste (Cosme y Damian)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 92,
    "sku": 91,
    "nombre": "Verde - Negro (Ogum)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Verde - Negro (Ogum)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 93,
    "sku": 92,
    "nombre": "Verde - Blanco - Negro (Santa Rita)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Verde - Blanco - Negro (Santa Rita)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 94,
    "sku": 93,
    "nombre": "Verde - Amarillo - Rojo (Caboclo)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Verde - Amarillo - Rojo (Caboclo)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 95,
    "sku": 94,
    "nombre": "Rosa - Blanco - Cel. (S. Nicolás)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Rosa - Blanco - Cel. (S. Nicolás)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 96,
    "sku": 95,
    "nombre": "Amarillo - Marrón (Onofre)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Amarillo - Marrón (Onofre)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 97,
    "sku": 96,
    "nombre": "Rosa - Negro (Xapana)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Rosa - Negro (Xapana)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 98,
    "sku": 97,
    "nombre": "Rojo - Blanco - Azul (Desatanudos)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Rojo - Blanco - Azul (Desatanudos)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 99,
    "sku": 98,
    "nombre": "Rojo - Verde - Negro (Ogum Mege)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Rojo - Verde - Negro (Ogum Mege)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 100,
    "sku": 99,
    "nombre": "Urkupiña - Rojo - Amarillo - Verde",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Urkupiña - Rojo - Amarillo - Verde",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 101,
    "sku": 100,
    "nombre": "Amarillo - Blanco - Rojo (Mística)",
    "marca": "",
    "linea": "Vela Larga Combinada",
    "fragancia": "Amarillo - Blanco - Rojo (Mística)",
    "costo": 227,
    "venta": 550,
    "stock": 0
  },
  {
    "id": 102,
    "sku": 101,
    "nombre": "vela corta - blanca",
    "marca": "",
    "linea": "Vela Corta",
    "fragancia": "blanca",
    "costo": 116,
    "venta": 400,
    "stock": 0
  },
  {
    "id": 103,
    "sku": 102,
    "nombre": "vela corta -  negra",
    "marca": "",
    "linea": "Vela Corta",
    "fragancia": "negra",
    "costo": 116,
    "venta": 400,
    "stock": 0
  },
  {
    "id": 104,
    "sku": 103,
    "nombre": "vela corta -  amarilla",
    "marca": "",
    "linea": "Vela Corta",
    "fragancia": "amarilla",
    "costo": 116,
    "venta": 400,
    "stock": 0
  },
  {
    "id": 105,
    "sku": 104,
    "nombre": "vela corta - roja",
    "marca": "",
    "linea": "Vela Corta",
    "fragancia": "roja",
    "costo": 116,
    "venta": 400,
    "stock": 0
  },
  {
    "id": 106,
    "sku": 105,
    "nombre": "vela corta - azul",
    "marca": "",
    "linea": "Vela Corta",
    "fragancia": "azul",
    "costo": 116,
    "venta": 400,
    "stock": 0
  },
  {
    "id": 107,
    "sku": 106,
    "nombre": "vela corta - naranja",
    "marca": "",
    "linea": "Vela Corta",
    "fragancia": "naranja",
    "costo": 116,
    "venta": 400,
    "stock": 0
  },
  {
    "id": 108,
    "sku": 107,
    "nombre": "vela corta -  verde",
    "marca": "",
    "linea": "Vela Corta",
    "fragancia": "verde",
    "costo": 116,
    "venta": 400,
    "stock": 0
  },
  {
    "id": 109,
    "sku": 108,
    "nombre": "vela corta -  rosa",
    "marca": "",
    "linea": "Vela Corta",
    "fragancia": "rosa",
    "costo": 116,
    "venta": 400,
    "stock": 0
  },
  {
    "id": 110,
    "sku": 109,
    "nombre": "vela corta -  celeste",
    "marca": "",
    "linea": "Vela Corta",
    "fragancia": "celeste",
    "costo": 116,
    "venta": 400,
    "stock": 0
  },
  {
    "id": 111,
    "sku": 110,
    "nombre": "vela corta -  violeta",
    "marca": "",
    "linea": "Vela Corta",
    "fragancia": "violeta",
    "costo": 116,
    "venta": 400,
    "stock": 0
  },
  {
    "id": 112,
    "sku": 111,
    "nombre": "vela corta -  marron",
    "marca": "",
    "linea": "Vela Corta",
    "fragancia": "marron",
    "costo": 116,
    "venta": 400,
    "stock": 0
  },
  {
    "id": 113,
    "sku": 113,
    "nombre": "Velon7 Blanco",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Velon7 Blanco",
    "costo": 2145,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 114,
    "sku": 114,
    "nombre": "Velon7 Rojo",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Velon7 Rojo",
    "costo": 2145,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 115,
    "sku": 115,
    "nombre": "Velon7 Celeste",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Velon7 Celeste",
    "costo": 2145,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 116,
    "sku": 116,
    "nombre": "Velon7 Negras",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Velon7 Negras",
    "costo": 2145,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 117,
    "sku": 117,
    "nombre": "Velon7 Verde",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Velon7 Verde",
    "costo": 2145,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 118,
    "sku": 118,
    "nombre": "Velon7 Violeta",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Velon7 Violeta",
    "costo": 2145,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 119,
    "sku": 119,
    "nombre": "Velon7 Azul",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Velon7 Azul",
    "costo": 2145,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 120,
    "sku": 120,
    "nombre": "Velon7 Rosa",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Velon7 Rosa",
    "costo": 2145,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 121,
    "sku": 121,
    "nombre": "Velon7 Naranja",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Velon7 Naranja",
    "costo": 2145,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 122,
    "sku": 122,
    "nombre": "Velon7 Marron",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Velon7 Marron",
    "costo": 2145,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 123,
    "sku": 123,
    "nombre": "Velon7 Lila",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Velon7 Lila",
    "costo": 2145,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 124,
    "sku": 124,
    "nombre": "Velon7 Miel",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Velon7 Miel",
    "costo": 2145,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 125,
    "sku": 125,
    "nombre": "Velon7 Fucsia",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Velon7 Fucsia",
    "costo": 2145,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 126,
    "sku": 126,
    "nombre": "Velon7 Amarillo",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Velon7 Amarillo",
    "costo": 2145,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 127,
    "sku": 127,
    "nombre": "Velon7 Blanco - Negro",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Negro",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 128,
    "sku": 128,
    "nombre": "Velon7 Verde - Blanco - Rojo",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Rojo",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 129,
    "sku": 129,
    "nombre": "Velon7 Rojo - Negro",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Negro",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 130,
    "sku": 130,
    "nombre": "Velon7 Negro - Rojo",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Rojo",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 131,
    "sku": 131,
    "nombre": "Velon7 Verde - Roja",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Roja",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 132,
    "sku": 132,
    "nombre": "Velon7 Rojo - Blanco",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Blanco",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 133,
    "sku": 133,
    "nombre": "Velon7 Blanco - Rojo",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Rojo",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 134,
    "sku": 134,
    "nombre": "Velon7 Rojo - Blanco - Negro",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Negro",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 135,
    "sku": 135,
    "nombre": "Velon7 Negro - Blanco",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Blanco",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 136,
    "sku": 136,
    "nombre": "Velon7 Verde - Negro",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Negro",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 137,
    "sku": 137,
    "nombre": "Velon7 Rojo - Verde",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Verde",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 138,
    "sku": 138,
    "nombre": "Velon7 Verde - Amarillo - Rojo",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Rojo",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 139,
    "sku": 139,
    "nombre": "Velon7 Blanco - Celeste",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Celeste",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 140,
    "sku": 140,
    "nombre": "Velon7 Amarillo - Verde",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Verde",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 141,
    "sku": 141,
    "nombre": "Velon7 Rosa - Celeste",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Celeste",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 142,
    "sku": 142,
    "nombre": "Velon7 Rojo - Verde - Negro",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Negro",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 143,
    "sku": 143,
    "nombre": "Velon7 Rosa - Blanco - Cel.",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Cel.",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 144,
    "sku": 144,
    "nombre": "Velon7 Verde - Blanco - Negro",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Negro",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 145,
    "sku": 145,
    "nombre": "Velon7 Amarillo - Marrón",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Marrón",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 146,
    "sku": 146,
    "nombre": "Velon7 Blanco - Amarillo",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Amarillo",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 147,
    "sku": 147,
    "nombre": "Velon7 Rosa - Negro",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Negro",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 148,
    "sku": 148,
    "nombre": "Velon7 Blanco - Verde",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Verde",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 149,
    "sku": 149,
    "nombre": "Velon7 - Rojo - Amarillo - Verde",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Verde",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 150,
    "sku": 150,
    "nombre": "Velon7 Amarillo - Blanco - Rojo",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Rojo",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 151,
    "sku": 151,
    "nombre": "Velon7 Rojo - Blanco - Azul",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Azul",
    "costo": 2210,
    "venta": 4500,
    "stock": 0
  },
  {
    "id": 152,
    "sku": 152,
    "nombre": "Velon 7 Dorado",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Dorado",
    "costo": 4268,
    "venta": 8500,
    "stock": 0
  },
  {
    "id": 153,
    "sku": 153,
    "nombre": "Velon 7 Plateado",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "Plateado",
    "costo": 4268,
    "venta": 8500,
    "stock": 0
  },
  {
    "id": 154,
    "sku": 154,
    "nombre": "Velon 7 7 Colores",
    "marca": "",
    "linea": "Velon 7 Dias",
    "fragancia": "7 Colores",
    "costo": 3518,
    "venta": 7000,
    "stock": 0
  }
];

export default PRODUCTOS;